const KINGDOMS_ITEM_NAMES = {
  "kingdoms:coin_copper": "Медная монета",
  "kingdoms:coin_silver": "Серебряная монета",
  "kingdoms:coin_gold": "Золотая монета",
  "kingdoms:coin_roll_copper": "Свёрток медных монет",
  "kingdoms:coin_roll_silver": "Свёрток серебряных монет",
  "kingdoms:flag": "Флаг поселения"
};

export const TRADE_BLOCKED_TYPE_IDS = new Set([
  "kingdoms:coin_copper",
  "kingdoms:coin_silver",
  "kingdoms:coin_gold",
  "kingdoms:coin_roll_copper",
  "kingdoms:coin_roll_silver"
]);

const WORD_RU = {
  acacia: "акациевые",
  activator: "активирующие",
  allium: "лук",
  amethyst: "аметистовый",
  ancient: "древние",
  andesite: "андезит",
  apple: "яблоко",
  armor: "броня",
  arrow: "стрела",
  axolotl: "аксолotl",
  azure: "голубой",
  baked: "печёный",
  bamboo: "бамбуковые",
  banner: "знамя",
  barrel: "бочка",
  basalt: "базальт",
  beef: "говядина",
  beetroot: "свёкла",
  birch: "берёзовые",
  black: "чёрные",
  blackstone: "чернит",
  blaze: "огненный",
  block: "блок",
  blue: "синие",
  boat: "лодка",
  bone: "костный",
  book: "книга",
  boots: "ботинки",
  bottle: "бутылочка",
  bow: "лук",
  bowl: "миска",
  bread: "хлеб",
  brick: "кирпич",
  brown: "коричневые",
  brush: "кисть",
  bucket: "ведро",
  bundle: "мешок",
  burn: "обожжённый",
  cake: "торт",
  calcite: "кальцит",
  campfire: "костёр",
  candle: "свеча",
  carrot: "морковь",
  cartography: "картографический",
  cauldron: "котёл",
  chain: "кольчужный",
  charcoal: "древесный уголь",
  chest: "сундук",
  chestplate: "нагрудник",
  chicken: "курица",
  chipped: "сколотый",
  chiseled: "резной",
  chorus: "хорус",
  clay: "глина",
  clock: "часы",
  coal: "уголь",
  cobblestone: "булыжник",
  cod: "треска",
  compass: "компас",
  composter: "компостер",
  cooked: "жареный",
  cookie: "печенье",
  copper: "медный",
  coral: "коралл",
  cracked: "потрескавшийся",
  crafting: "верстак",
  creeper: "крипер",
  crimson: "багровые",
  crossbow: "арбалет",
  crying: "плачущий",
  cyan: "бирюзовые",
  dark: "тёмный",
  deepslate: "глубинный сланец",
  detector: "датчик",
  diamond: "алмазный",
  dirt: "земля",
  disc: "пластинка",
  dragon: "дракон",
  dried: "сушёный",
  dripstone: "капельник",
  egg: "яйцо",
  elytra: "элитры",
  emerald: "изумруд",
  enchanted: "зачарованное",
  end: "энд",
  ender: "эндер",
  eye: "глаз",
  feather: "перо",
  fermented: "ферментированный",
  fern: "папоротник",
  firework: "фейерверк",
  fish: "рыба",
  fishing: "удочка",
  flint: "кремниевый",
  flower: "цветок",
  frame: "рамка",
  fried: "жареный",
  fruit: "плод",
  furnace: "печь",
  ghast: "гаста",
  glass: "стекло",
  glow: "светящийся",
  glowstone: "светокамень",
  gold: "золотой",
  golden: "золотой",
  granite: "гранит",
  grass: "травяной",
  gravel: "гравий",
  gray: "серые",
  green: "зелёные",
  grindstone: "точило",
  gunpowder: "порох",
  hay: "сено",
  heart: "сердце",
  helmet: "шлем",
  hoe: "мотыга",
  honey: "мёд",
  honeycomb: "соты",
  hopper: "воронка",
  ink: "чернильный",
  iron: "железный",
  item: "предмет",
  jungle: "джунглевые",
  kelp: "ламинария",
  lapis: "лазурит",
  lava: "лавы",
  lead: "поводок",
  leather: "кожаный",
  leaves: "листья",
  leg: "нога",
  leggings: "поножи",
  light: "светлые",
  lime: "лаймовые",
  log: "бревно",
  loom: "ткацкий",
  magenta: "пурпурные",
  magma: "магма",
  mangrove: "манgровые",
  map: "карта",
  melon: "арбуз",
  milk: "молока",
  minecart: "вагонетка",
  mossy: "замшелый",
  mushroom: "гриб",
  mutton: "баранина",
  name: "имени",
  nautilus: "наутilus",
  nether: "незерский",
  netherite: "незеритовый",
  nugget: "самородок",
  oak: "дубовые",
  obsidian: "обсидиан",
  of: "",
  orange: "оранжевые",
  ore: "руда",
  oxeye: "ромашка",
  paper: "бумага",
  pearl: "жемчуг",
  phantom: "фантом",
  pickaxe: "кирка",
  pie: "пирог",
  pink: "розовые",
  planks: "доски",
  podzol: "podzol",
  pointed: "острый",
  poison: "ядовитый",
  potato: "картофель",
  potion: "зелье",
  powered: "электрические",
  prismarine: "приzmариновый",
  pufferfish: "иглобрюх",
  pumpkin: "тыква",
  purple: "фиолетовые",
  quartz: "кварц",
  rabbit: "кролик",
  rail: "рельсы",
  raw: "сырой",
  recovery: "восстановления",
  red: "красные",
  redstone: "редстоун",
  repeater: "повторитель",
  rocket: "ракета",
  rotten: "гнилой",
  saddle: "седло",
  salmon: "лосось",
  sand: "песок",
  sandstone: "песчаник",
  sapling: "саженец",
  scute: "щиток",
  sea: "морской",
  seeds: "семена",
  shard: "осколок",
  shears: "ножницы",
  shield: "щит",
  shulker: "шалкер",
  sign: "табличка",
  skull: "череп",
  slime: "слизь",
  smithing: "кузнечный",
  smoker: "коптильня",
  snow: "снежный",
  soul: "душ",
  soup: "суп",
  spawn: "призыва",
  spider: "паучий",
  spruce: "еловые",
  spyglass: "подзорная труба",
  stained: "окрашенное",
  steak: "стейк",
  stick: "палка",
  sticky: "липкий",
  stone: "каменный",
  stonecutter: "камнерез",
  string: "нить",
  stripped: "обтёсанное",
  sugar: "сахар",
  suspicious: "подозрительный",
  sweet: "сладкие",
  sword: "меч",
  table: "стол",
  tag: "бирка",
  tall: "высокий",
  terracotta: "терракота",
  tnt: "динамит",
  torch: "факел",
  totem: "тотем",
  transparent: "прозрачное",
  trapdoor: "люк",
  trident: "трезубец",
  tropical: "тропическая",
  turtle: "черепаший",
  undying: "бессмертия",
  warped: "искажённые",
  water: "воды",
  wheat: "пшеница",
  white: "белые",
  wool: "шерсть",
  yellow: "жёлтые"
};

const ITEM_OVERRIDES = {
  "minecraft:air": "Воздух",
  "minecraft:diamond": "Алмаз",
  "minecraft:emerald": "Изумруд",
  "minecraft:gold_ingot": "Золотой слиток",
  "minecraft:iron_ingot": "Железный слиток",
  "minecraft:copper_ingot": "Медный слиток",
  "minecraft:netherite_ingot": "Незеритовый слиток",
  "minecraft:coal": "Уголь",
  "minecraft:charcoal": "Древесный уголь",
  "minecraft:redstone": "Редстоун",
  "minecraft:lapis_lazuli": "Лазурит",
  "minecraft:quartz": "Кварц",
  "minecraft:flint": "Кремень",
  "minecraft:stick": "Палка",
  "minecraft:string": "Нить",
  "minecraft:feather": "Перо",
  "minecraft:gunpowder": "Порох",
  "minecraft:bone": "Кость",
  "minecraft:slime_ball": "Слизь",
  "minecraft:ender_pearl": "Жемчуг Эндера",
  "minecraft:blaze_rod": "Огненный стержень",
  "minecraft:ghast_tear": "Слеза гаста",
  "minecraft:nether_star": "Звезда Незера",
  "minecraft:shulker_shell": "Панцирь шалкера",
  "minecraft:totem_of_undying": "Тотем бессмертия",
  "minecraft:elytra": "Элитры",
  "minecraft:trident": "Трезубец",
  "minecraft:heart_of_the_sea": "Сердце моря",
  "minecraft:nautilus_shell": "Раковина наутilus",
  "minecraft:experience_bottle": "Пузырёк опыта",
  "minecraft:enchanted_golden_apple": "Зачарованное золотое яблоко",
  "minecraft:golden_apple": "Золотое яблоко",
  "minecraft:apple": "Яблоко",
  "minecraft:bread": "Хлеб",
  "minecraft:cooked_beef": "Стейк",
  "minecraft:cooked_porkchop": "Жареная свинина",
  "minecraft:cooked_chicken": "Жареная курица",
  "minecraft:cooked_mutton": "Жареная баранина",
  "minecraft:cooked_rabbit": "Жареный кролик",
  "minecraft:cooked_cod": "Жареная треска",
  "minecraft:cooked_salmon": "Жареный лосось",
  "minecraft:beef": "Сырая говядина",
  "minecraft:porkchop": "Сырая свинина",
  "minecraft:chicken": "Сырая курятина",
  "minecraft:mutton": "Сырая баранина",
  "minecraft:rabbit": "Сырой кролик",
  "minecraft:cod": "Сырой треска",
  "minecraft:salmon": "Сырой лосось",
  "minecraft:tropical_fish": "Тропическая рыба",
  "minecraft:pufferfish": "Иглобрюх",
  "minecraft:potato": "Картофель",
  "minecraft:baked_potato": "Печёный картофель",
  "minecraft:poisonous_potato": "Ядовитый картофель",
  "minecraft:carrot": "Морковь",
  "minecraft:golden_carrot": "Золотая морковь",
  "minecraft:beetroot": "Свёкла",
  "minecraft:beetroot_soup": "Свекольный суп",
  "minecraft:mushroom_stew": "Грибной суп",
  "minecraft:rabbit_stew": "Кроличий суп",
  "minecraft:suspicious_stew": "Подозрительный суп",
  "minecraft:melon_slice": "Ломтик арбуза",
  "minecraft:pumpkin_pie": "Тыквенный пирог",
  "minecraft:cookie": "Печенье",
  "minecraft:cake": "Торт",
  "minecraft:honey_bottle": "Бутылочка мёда",
  "minecraft:milk_bucket": "Ведро молока",
  "minecraft:water_bucket": "Ведро воды",
  "minecraft:lava_bucket": "Ведро лавы",
  "minecraft:bucket": "Ведро",
  "minecraft:bow": "Лук",
  "minecraft:crossbow": "Арбалет",
  "minecraft:arrow": "Стрела",
  "minecraft:spectral_arrow": "Спектральная стрела",
  "minecraft:shield": "Щит",
  "minecraft:torch": "Факел",
  "minecraft:soul_torch": "Факел душ",
  "minecraft:lantern": "Фонарь",
  "minecraft:soul_lantern": "Фонарь душ",
  "minecraft:campfire": "Костёр",
  "minecraft:soul_campfire": "Костёр душ",
  "minecraft:compass": "Компас",
  "minecraft:recovery_compass": "Компас восстановления",
  "minecraft:clock": "Часы",
  "minecraft:spyglass": "Подзорная труба",
  "minecraft:fishing_rod": "Удочка",
  "minecraft:flint_and_steel": "Огниво",
  "minecraft:shears": "Ножницы",
  "minecraft:lead": "Поводок",
  "minecraft:name_tag": "Бирка",
  "minecraft:saddle": "Седло",
  "minecraft:brush": "Кисть",
  "minecraft:book": "Книга",
  "minecraft:writable_book": "Книга с пером",
  "minecraft:written_book": "Написанная книга",
  "minecraft:paper": "Бумага",
  "minecraft:map": "Карта",
  "minecraft:filled_map": "Карта",
  "minecraft:firework_rocket": "Фейерверк",
  "minecraft:leather": "Кожа",
  "minecraft:leather_helmet": "Кожаный шлем",
  "minecraft:leather_chestplate": "Кожаный нагрудник",
  "minecraft:leather_leggings": "Кожаные поножи",
  "minecraft:leather_boots": "Кожаные ботинки",
  "minecraft:chainmail_helmet": "Кольчужный шлем",
  "minecraft:chainmail_chestplate": "Кольчужный нагрудник",
  "minecraft:chainmail_leggings": "Кольчужные поножи",
  "minecraft:chainmail_boots": "Кольчужные ботинки",
  "minecraft:iron_helmet": "Железный шлем",
  "minecraft:iron_chestplate": "Железный нагрудник",
  "minecraft:iron_leggings": "Железные поножи",
  "minecraft:iron_boots": "Железные ботинки",
  "minecraft:golden_helmet": "Золотой шлем",
  "minecraft:golden_chestplate": "Золотой нагрудник",
  "minecraft:golden_leggings": "Золотые поножи",
  "minecraft:golden_boots": "Золотые ботинки",
  "minecraft:diamond_helmet": "Алмазный шлем",
  "minecraft:diamond_chestplate": "Алмазный нагрудник",
  "minecraft:diamond_leggings": "Алмазные поножи",
  "minecraft:diamond_boots": "Алмазные ботинки",
  "minecraft:netherite_helmet": "Незеритовый шлем",
  "minecraft:netherite_chestplate": "Незеритовый нагрудник",
  "minecraft:netherite_leggings": "Незеритовые поножи",
  "minecraft:netherite_boots": "Незеритовые ботинки",
  "minecraft:wooden_sword": "Деревянный меч",
  "minecraft:stone_sword": "Каменный меч",
  "minecraft:iron_sword": "Железный меч",
  "minecraft:golden_sword": "Золотой меч",
  "minecraft:diamond_sword": "Алмазный меч",
  "minecraft:netherite_sword": "Незеритовый меч",
  "minecraft:wooden_pickaxe": "Деревянная кирка",
  "minecraft:stone_pickaxe": "Каменная кирка",
  "minecraft:iron_pickaxe": "Железная кирка",
  "minecraft:golden_pickaxe": "Золотая кирка",
  "minecraft:diamond_pickaxe": "Алмазная кирка",
  "minecraft:netherite_pickaxe": "Незеритовая кирка",
  "minecraft:wooden_axe": "Деревянный топор",
  "minecraft:stone_axe": "Каменный топор",
  "minecraft:iron_axe": "Железный топор",
  "minecraft:golden_axe": "Золотой топор",
  "minecraft:diamond_axe": "Алмазный топор",
  "minecraft:netherite_axe": "Незеритовый топор",
  "minecraft:wooden_shovel": "Деревянная лопата",
  "minecraft:stone_shovel": "Каменная лопата",
  "minecraft:iron_shovel": "Железная лопата",
  "minecraft:golden_shovel": "Золотая лопата",
  "minecraft:diamond_shovel": "Алмазная лопата",
  "minecraft:netherite_shovel": "Незеритовая лопата",
  "minecraft:wooden_hoe": "Деревянная мотыга",
  "minecraft:stone_hoe": "Каменная мотыга",
  "minecraft:iron_hoe": "Железная мотыга",
  "minecraft:golden_hoe": "Золотая мотыга",
  "minecraft:diamond_hoe": "Алмазная мотыга",
  "minecraft:netherite_hoe": "Незеритовая мотыга"
};

function capitalize(text) {
  if (!text) return text;
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function translateParts(id) {
  const parts = id.split("_").filter(Boolean);
  const translated = parts
    .map((part) => WORD_RU[part])
    .filter((part) => part && part.length);
  if (!translated.length) return undefined;
  return capitalize(translated.join(" "));
}

export function getItemDisplayNameRu(typeId) {
  if (!typeId) return "Предмет";
  if (KINGDOMS_ITEM_NAMES[typeId]) return KINGDOMS_ITEM_NAMES[typeId];
  if (ITEM_OVERRIDES[typeId]) return ITEM_OVERRIDES[typeId];

  const id = typeId.includes(":") ? typeId.split(":").slice(1).join(":") : typeId;
  const translated = translateParts(id);
  if (translated) return translated;

  return capitalize(id.replace(/_/g, " "));
}

export function formatItemButtonLabel(displayName, maxLineLength = 18) {
  const name = String(displayName ?? "").trim();
  if (name.length <= maxLineLength) return name;

  const mid = Math.ceil(name.length / 2);
  let splitAt = name.lastIndexOf(" ", mid + 4);
  if (splitAt <= 0) splitAt = mid;
  const line1 = name.slice(0, splitAt).trim();
  const line2 = name.slice(splitAt).trim();
  return line2 ? `${line1}\n${line2}` : line1;
}

export function isTradeBlockedItem(typeId) {
  return TRADE_BLOCKED_TYPE_IDS.has(typeId);
}
